# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Aashis Khanal
title: Ph.D. Student
email: sraashis@gmail.com
website: https://sraashis.github.io/

# Social links
twitter_username: sraashis
github_username:  sraashis
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: sraashis
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Aashis and I'm a Ph.D. student at Georgia State University.
  My research focus is on use of Machine Learning, Computer Vision for medical image analysis and diagnosis.
  I work with <mark>Pytorch</mark>.

# Education Section
# education_title: Education

# Experience Section
# experience_title: Experience

# Publications Section
# publication_title: Publications

# Projects Section
# projects_title: Projects


# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
